/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package connect4;

import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Toshiba
 */
public class Game extends javax.swing.JFrame {

    /**
     * Creates new form Game
     */
    connect4WithoutGUI gUI = new connect4WithoutGUI();
    String Arrayofimg[] = {"red.jpg", "yellow.jpg", "white.png"};
    public JLabel[][] grid = new JLabel[6][7];
    boolean control = false;

    public Game() {
        initComponents();
        grid = new JLabel[][]{
            {i1, i2, i3, i4, i5, i6},
            {i7, i8, i9, i10, i11, i12},
            {i13, i14, i15, i16, i17, i18},
            {i19, i20, i21, i22, i23, i24},
            {i25, i26, i27, i28, i29, i30},
            {i31, i32, i33, i34, i35, i36},
            {i37, i38, i39, i40, i41, i42}
        };

        this.setLocationRelativeTo(
                this);
        showicon();

        JOptionPane.showMessageDialog(this,
                "Welcome to Connect 4. Hope you enjoy the game.");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playertxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Player1 = new javax.swing.JLabel();
        Player2 = new javax.swing.JLabel();
        PlayBtu = new javax.swing.JButton();
        i1 = new javax.swing.JLabel();
        i2 = new javax.swing.JLabel();
        i3 = new javax.swing.JLabel();
        i4 = new javax.swing.JLabel();
        i5 = new javax.swing.JLabel();
        i6 = new javax.swing.JLabel();
        i7 = new javax.swing.JLabel();
        i8 = new javax.swing.JLabel();
        i9 = new javax.swing.JLabel();
        i10 = new javax.swing.JLabel();
        i11 = new javax.swing.JLabel();
        i12 = new javax.swing.JLabel();
        i14 = new javax.swing.JLabel();
        i15 = new javax.swing.JLabel();
        i16 = new javax.swing.JLabel();
        i17 = new javax.swing.JLabel();
        i13 = new javax.swing.JLabel();
        i18 = new javax.swing.JLabel();
        i20 = new javax.swing.JLabel();
        i21 = new javax.swing.JLabel();
        i22 = new javax.swing.JLabel();
        i23 = new javax.swing.JLabel();
        i19 = new javax.swing.JLabel();
        i24 = new javax.swing.JLabel();
        i25 = new javax.swing.JLabel();
        i26 = new javax.swing.JLabel();
        i27 = new javax.swing.JLabel();
        i28 = new javax.swing.JLabel();
        i29 = new javax.swing.JLabel();
        i30 = new javax.swing.JLabel();
        i31 = new javax.swing.JLabel();
        i32 = new javax.swing.JLabel();
        i33 = new javax.swing.JLabel();
        i34 = new javax.swing.JLabel();
        i35 = new javax.swing.JLabel();
        i36 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Playerone = new javax.swing.JLabel();
        PlayerTwo = new javax.swing.JLabel();
        i37 = new javax.swing.JLabel();
        i38 = new javax.swing.JLabel();
        i39 = new javax.swing.JLabel();
        i40 = new javax.swing.JLabel();
        i41 = new javax.swing.JLabel();
        i42 = new javax.swing.JLabel();
        cdf = new javax.swing.JButton();
        A = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("colum select");

        jLabel2.setText("player Chooser :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/connect4/tolgacon.png"))); // NOI18N

        jButton1.setText("Exit");

        jButton2.setText("Reset Game");

        jLabel5.setText("Player 1:");

        jLabel6.setText("Player 2:");

        Player1.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 14)); // NOI18N
        Player1.setText("Ahmet");

        Player2.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        Player2.setText("maya");

        PlayBtu.setText("Play");
        PlayBtu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayBtuActionPerformed(evt);
            }
        });

        i1.setBackground(new java.awt.Color(255, 255, 0));
        i1.setToolTipText("");

        i2.setToolTipText("");

        i3.setToolTipText("");

        i4.setToolTipText("");

        i5.setToolTipText("");

        i6.setToolTipText("");

        i7.setToolTipText("");

        i8.setToolTipText("");

        i9.setToolTipText("");

        i10.setToolTipText("");

        i11.setToolTipText("");

        i12.setToolTipText("");

        i14.setToolTipText("");

        i15.setToolTipText("");

        i16.setToolTipText("");

        i17.setToolTipText("");

        i13.setToolTipText("");

        i18.setToolTipText("");

        i20.setToolTipText("");

        i21.setToolTipText("");

        i22.setToolTipText("");

        i23.setToolTipText("");

        i19.setToolTipText("");

        i24.setToolTipText("");

        i25.setToolTipText("");

        i26.setToolTipText("");

        i27.setToolTipText("");

        i28.setToolTipText("");

        i29.setToolTipText("");

        i30.setToolTipText("");

        i31.setToolTipText("");

        i32.setToolTipText("");

        i33.setToolTipText("");

        i34.setToolTipText("");

        i35.setToolTipText("");

        i36.setToolTipText("");

        jLabel7.setText("infor");

        Playerone.setText("Player one is Red");

        PlayerTwo.setText("Player two is bule");

        i37.setToolTipText("");

        i38.setToolTipText("");

        i39.setToolTipText("");

        i40.setToolTipText("");

        i41.setToolTipText("");

        i42.setToolTipText("");

        cdf.setText("jButton3");

        A.setText("jButton3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 120, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(jButton2)
                        .addGap(40, 40, 40)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(661, 661, 661)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Player2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Player1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(i2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(i8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addComponent(i14))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(i3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(i9)
                                .addGap(35, 35, 35)
                                .addComponent(i15))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(i4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(i10)
                                .addGap(36, 36, 36)
                                .addComponent(i16))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(i5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(i11)
                                .addGap(36, 36, 36)
                                .addComponent(i17)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(i21)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(i19)
                                    .addComponent(i20)
                                    .addComponent(i22)
                                    .addComponent(i23)
                                    .addComponent(i24))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(i28)
                            .addComponent(i29)
                            .addComponent(i30)
                            .addComponent(i25)
                            .addComponent(i26)
                            .addComponent(i27))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(i35)
                            .addComponent(i36)
                            .addComponent(i31)
                            .addComponent(i34)
                            .addComponent(i32)
                            .addComponent(i33)
                            .addComponent(cdf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(A, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(i1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(i7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(i13))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(i6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(i12)
                        .addGap(36, 36, 36)
                        .addComponent(i18)))
                .addGap(0, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(i41)
                    .addComponent(i42)
                    .addComponent(i37)
                    .addComponent(i40)
                    .addComponent(i38)
                    .addComponent(i39))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(playertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(285, 285, 285)
                                .addComponent(PlayBtu, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(269, 269, 269)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(250, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PlayerTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Playerone, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(77, 77, 77))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton1))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Player1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Player2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(i1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(i7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(i13)))
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(i2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(i8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(i14))))
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(i3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(i9)
                                            .addComponent(i15))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(i4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(i10))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(i16)))
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(i5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(i11))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(i17))))
                            .addComponent(PlayBtu, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(i6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(i12))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(i18))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(i19)
                                        .addComponent(i25))
                                    .addGap(6, 6, 6)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(i20)
                                        .addComponent(i26))
                                    .addGap(6, 6, 6)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(i21)
                                        .addComponent(i27))
                                    .addGap(13, 13, 13)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(i22)
                                        .addComponent(i28))
                                    .addGap(9, 9, 9)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(i23)
                                            .addGap(11, 11, 11)
                                            .addComponent(i24))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(i29)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(i30)
                                            .addGap(5, 5, 5))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(i41)
                                        .addGap(6, 6, 6)
                                        .addComponent(i42)
                                        .addGap(6, 6, 6)
                                        .addComponent(i37)
                                        .addGap(13, 13, 13)
                                        .addComponent(i38)
                                        .addGap(9, 9, 9)
                                        .addComponent(i39)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(i40))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(i35)
                                        .addGap(6, 6, 6)
                                        .addComponent(i36)
                                        .addGap(6, 6, 6)
                                        .addComponent(i31)
                                        .addGap(13, 13, 13)
                                        .addComponent(i32)
                                        .addGap(9, 9, 9)
                                        .addComponent(i33)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(i34))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(playertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addGap(35, 35, 35)
                                .addComponent(Playerone, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(PlayerTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(cdf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(A, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PlayBtuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayBtuActionPerformed
        // TODO add your handling code here:

        int turn = 1;
        String player = "R";
        boolean winner = false;

        //play a turn
        while (winner == false && turn <= 42) {
            boolean validPlay;
            int play;
            do {
                display();
                JOptionPane.showMessageDialog(this, "Player " + player + ", choose a column: ");
                try {
                    Thread.sleep(5000);
                } catch (InterruptedException ex) {
                    Logger.getLogger(Game.class.getName()).log(Level.SEVERE, null, ex);
                }
                play = Integer.parseInt(playertxt.getText());

                //validate play
                validPlay = validate(play);

            } while (validPlay == false);

            //drop the checker
            for (int row = grid.length - 1; row >= 0; row--) {
                if (grid[row][play].getText().equals("")) {
                    grid[row][play].setText(player);
                   
                    break;
                }
            }

            //determine if there is a winner
            winner = isWinner(player);

            //switch players
            if ("R".equals(player)) {
                player = "B";
            } else {
                player = "R";
            }

            turn++;
        }
        display();

        if (winner) {
            if ("R".equals(player)) {
                JOptionPane.showMessageDialog(this, "Black won");
            } else {
                JOptionPane.showMessageDialog(this, " Red won");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Tie game");
        }

//        if ("A".equals(player1txt.getText())) {
//            for (int i = 0; i < grid.length; i++) {
//                for (int j = 0; j < grid.length; j++) {
//
//                    grid[i][j].setIcon(new javax.swing.ImageIcon(getClass().getResource(Arrayofimg[0])));
//
//                }
//            }
//        }

    }//GEN-LAST:event_PlayBtuActionPerformed

    public void display() {
        // System.out.println(" 0 1 2 3 4 5 6");
        // System.out.println("---------------");
        for (int row = 0; row < grid.length; row++) {
            for (int col = 0; col < grid[0].length; col++) {
                grid[row][col].setText(grid[row][col].getText());

            }
        }
    }

    public boolean validate(int column) {
        //valid column?
        if (column < 0 || column > grid[0].length) {
            return false;
        }

        //full column?
        if (!grid[0][column].getText().equals("")) {
            return false;
        }

        return true;
    }

    public boolean isWinner(String player) {
        //check for 4 across
        for (int row = 0; row < grid.length; row++) {
            for (int col = 0; col < grid[0].length - 3; col++) {
                if (grid[row][col].getText().equals(player)
                        && grid[row][col + 1].getText().equals(player)
                        && grid[row][col + 2].getText().equals(player)
                        && grid[row][col + 3].getText().equals(player)) {
                    return true;
                }
            }
        }
        //check for 4 up and down
        for (int row = 0; row < grid.length - 3; row++) {
            for (int col = 0; col < grid[0].length; col++) {
                if (grid[row][col].getText().equals(player)
                        && grid[row + 1][col].getText().equals(player)
                        && grid[row + 2][col].getText().equals(player)
                        && grid[row + 3][col].getText().equals(player)) {
                    return true;
                }
            }
        }
        //check upward diagonal
        for (int row = 3; row < grid.length; row++) {
            for (int col = 0; col < grid[0].length - 3; col++) {
                if (grid[row][col].getText().equals(player)
                        && grid[row - 1][col + 1].getText().equals(player)
                        && grid[row - 2][col + 2].getText().equals(player)
                        && grid[row - 3][col + 3].getText().equals(player)) {
                    return true;
                }
            }
        }
        //check downward diagonal
        for (int row = 0; row < grid.length - 3; row++) {
            for (int col = 0; col < grid[0].length - 3; col++) {
                if (grid[row][col].getText().equals(player)
                        && grid[row + 1][col + 1].getText().equals(player)
                        && grid[row + 2][col + 2].getText().equals(player)
                        && grid[row + 3][col + 3].getText().equals(player)) {
                    return true;
                }
            }
        }
        return false;
    }

    /**
     * @param args the command line arguments
     */
    void showicon() {
        int size = 100;
        cdf.setIcon(new javax.swing.ImageIcon(getClass().getResource(Arrayofimg[2])));
        getContentPane().add(cdf);
        cdf.setBounds(10, size, 60, 50);

        A.setIcon(new javax.swing.ImageIcon(getClass().getResource(Arrayofimg[2])));
        getContentPane().add(A);
        size = size + 60;
        A.setBounds(7, size, 60, 50);
        size = size + 60;
        i3.setIcon(new javax.swing.ImageIcon(getClass().getResource(Arrayofimg[2])));
        getContentPane().add(i3);
        i3.setBounds(7, size, 50, 62);
        size = size + 60;
        i4.setIcon(new javax.swing.ImageIcon(getClass().getResource(Arrayofimg[2])));
        getContentPane().add(i4);
        i4.setBounds(7, size, 50, 62);

        size = size + 60;
        i5.setIcon(new javax.swing.ImageIcon(getClass().getResource(Arrayofimg[2])));
        getContentPane().add(i5);
        i5.setBounds(7, size, 50, 62);

        size = size + 60;
        i6.setIcon(new javax.swing.ImageIcon(getClass().getResource(Arrayofimg[2])));
        getContentPane().add(i6);
        i6.setBounds(7, size, 50, 62);

        /// culom2
        size = 100;

        i7.setIcon(new javax.swing.ImageIcon(getClass().getResource(Arrayofimg[2])));
        getContentPane().add(i7);
        i7.setBounds(60, size, 50, 62);

        size = size + 60;
        i8.setIcon(new javax.swing.ImageIcon(getClass().getResource(Arrayofimg[2])));
        getContentPane().add(i8);
        i8.setBounds(60, size, 50, 62);

        size = size + 60;
        i9.setIcon(new javax.swing.ImageIcon(getClass().getResource(Arrayofimg[2])));
        getContentPane().add(i9);
        i9.setBounds(60, size, 50, 62);

        size = size + 60;
        i10.setIcon(new javax.swing.ImageIcon(getClass().getResource(Arrayofimg[2])));
        getContentPane().add(i10);
        i10.setBounds(60, size, 50, 62);

        size = size + 60;
        i11.setIcon(new javax.swing.ImageIcon(getClass().getResource(Arrayofimg[2])));
        getContentPane().add(i11);
        i11.setBounds(60, size, 50, 62);

        size = size + 60;
        i12.setIcon(new javax.swing.ImageIcon(getClass().getResource(Arrayofimg[2])));
        getContentPane().add(i12);
        i12.setBounds(60, size, 50, 62);

        /// culom3
        size = 100;
        int row = 120;

        i13.setIcon(new javax.swing.ImageIcon(getClass().getResource(Arrayofimg[2])));
        getContentPane().add(i13);
        i13.setBounds(row, size, 50, 62);

        size = size + 60;

        i14.setIcon(new javax.swing.ImageIcon(getClass().getResource(Arrayofimg[2])));
        getContentPane().add(i14);
        i14.setBounds(row, size, 50, 62);

        size = size + 60;

        i15.setIcon(new javax.swing.ImageIcon(getClass().getResource(Arrayofimg[2])));
        getContentPane().add(i15);
        i15.setBounds(row, size, 50, 62);

        size = size + 60;
        i16.setIcon(new javax.swing.ImageIcon(getClass().getResource(Arrayofimg[2])));
        getContentPane().add(i16);
        i16.setBounds(row, size, 50, 62);

        size = size + 60;
        i17.setIcon(new javax.swing.ImageIcon(getClass().getResource(Arrayofimg[2])));
        getContentPane().add(i17);
        i17.setBounds(row, size, 50, 62);

        size = size + 60;
        i18.setIcon(new javax.swing.ImageIcon(getClass().getResource(Arrayofimg[2])));
        getContentPane().add(i18);
        i18.setBounds(row, size, 50, 62);

        /// culom3
        size = 100;
        row = row + 60;

        i19.setIcon(new javax.swing.ImageIcon(getClass().getResource(Arrayofimg[2])));
        getContentPane().add(i19);
        i19.setBounds(row, size, 50, 62);

        size = size + 60;

        i20.setIcon(new javax.swing.ImageIcon(getClass().getResource(Arrayofimg[2])));
        getContentPane().add(i20);
        i20.setBounds(row, size, 50, 62);

        size = size + 60;

        i21.setIcon(new javax.swing.ImageIcon(getClass().getResource(Arrayofimg[2])));
        getContentPane().add(i21);
        i21.setBounds(row, size, 50, 62);

        size = size + 60;
        i22.setIcon(new javax.swing.ImageIcon(getClass().getResource(Arrayofimg[2])));
        getContentPane().add(i22);
        i22.setBounds(row, size, 50, 62);

        size = size + 60;
        i23.setIcon(new javax.swing.ImageIcon(getClass().getResource(Arrayofimg[2])));
        getContentPane().add(i23);
        i23.setBounds(row, size, 50, 62);

        size = size + 60;
        i24.setIcon(new javax.swing.ImageIcon(getClass().getResource(Arrayofimg[2])));
        getContentPane().add(i24);
        i24.setBounds(row, size, 50, 62);
        /// culom5
        size = 100;
        row = row + 60;

        i25.setIcon(new javax.swing.ImageIcon(getClass().getResource(Arrayofimg[2])));
        getContentPane().add(i25);
        i25.setBounds(row, size, 50, 62);

        size = size + 60;

        i26.setIcon(new javax.swing.ImageIcon(getClass().getResource(Arrayofimg[2])));
        getContentPane().add(i26);
        i26.setBounds(row, size, 50, 62);

        size = size + 60;

        i27.setIcon(new javax.swing.ImageIcon(getClass().getResource(Arrayofimg[2])));
        getContentPane().add(i27);
        i27.setBounds(row, size, 50, 62);

        size = size + 60;
        i28.setIcon(new javax.swing.ImageIcon(getClass().getResource(Arrayofimg[2])));
        getContentPane().add(i28);
        i28.setBounds(row, size, 50, 62);

        size = size + 60;
        i29.setIcon(new javax.swing.ImageIcon(getClass().getResource(Arrayofimg[2])));
        getContentPane().add(i29);
        i29.setBounds(row, size, 50, 62);

        size = size + 60;
        i30.setIcon(new javax.swing.ImageIcon(getClass().getResource(Arrayofimg[2])));
        getContentPane().add(i30);
        i30.setBounds(row, size, 50, 62);

        /// culom5
        size = 100;
        row = row + 60;

        i31.setIcon(new javax.swing.ImageIcon(getClass().getResource(Arrayofimg[2])));
        getContentPane().add(i31);
        i31.setBounds(row, size, 50, 62);

        size = size + 60;

        i32.setIcon(new javax.swing.ImageIcon(getClass().getResource(Arrayofimg[2])));
        getContentPane().add(i32);
        i32.setBounds(row, size, 50, 62);

        size = size + 60;

        i33.setIcon(new javax.swing.ImageIcon(getClass().getResource(Arrayofimg[2])));
        getContentPane().add(i33);
        i33.setBounds(row, size, 50, 62);

        size = size + 60;
        i34.setIcon(new javax.swing.ImageIcon(getClass().getResource(Arrayofimg[2])));
        getContentPane().add(i34);
        i34.setBounds(row, size, 50, 62);

        size = size + 60;
        i35.setIcon(new javax.swing.ImageIcon(getClass().getResource(Arrayofimg[2])));
        getContentPane().add(i35);
        i35.setBounds(row, size, 50, 62);

        size = size + 60;
        i36.setIcon(new javax.swing.ImageIcon(getClass().getResource(Arrayofimg[2])));
        getContentPane().add(i36);
        i36.setBounds(row, size, 50, 62);

        /// culom5
        size = 100;
        row = row + 60;

        i37.setIcon(new javax.swing.ImageIcon(getClass().getResource(Arrayofimg[2])));
        getContentPane().add(i37);
        i37.setBounds(row, size, 50, 62);

        size = size + 60;

        i38.setIcon(new javax.swing.ImageIcon(getClass().getResource(Arrayofimg[2])));
        getContentPane().add(i38);
        i38.setBounds(row, size, 50, 62);

        size = size + 60;

        i39.setIcon(new javax.swing.ImageIcon(getClass().getResource(Arrayofimg[2])));
        getContentPane().add(i39);
        i39.setBounds(row, size, 50, 62);

        size = size + 60;
        i40.setIcon(new javax.swing.ImageIcon(getClass().getResource(Arrayofimg[2])));
        getContentPane().add(i40);
        i40.setBounds(row, size, 50, 62);

        size = size + 60;
        i41.setIcon(new javax.swing.ImageIcon(getClass().getResource(Arrayofimg[2])));
        getContentPane().add(i41);
        i41.setBounds(row, size, 50, 62);

        size = size + 60;
        i42.setIcon(new javax.swing.ImageIcon(getClass().getResource(Arrayofimg[2])));
        getContentPane().add(i42);
        i42.setBounds(row, size, 50, 62);

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A;
    private javax.swing.JButton PlayBtu;
    private javax.swing.JLabel Player1;
    private javax.swing.JLabel Player2;
    private javax.swing.JLabel PlayerTwo;
    private javax.swing.JLabel Playerone;
    private javax.swing.JButton cdf;
    private javax.swing.JLabel i1;
    private javax.swing.JLabel i10;
    private javax.swing.JLabel i11;
    private javax.swing.JLabel i12;
    private javax.swing.JLabel i13;
    private javax.swing.JLabel i14;
    private javax.swing.JLabel i15;
    private javax.swing.JLabel i16;
    private javax.swing.JLabel i17;
    private javax.swing.JLabel i18;
    private javax.swing.JLabel i19;
    private javax.swing.JLabel i2;
    private javax.swing.JLabel i20;
    private javax.swing.JLabel i21;
    private javax.swing.JLabel i22;
    private javax.swing.JLabel i23;
    private javax.swing.JLabel i24;
    private javax.swing.JLabel i25;
    private javax.swing.JLabel i26;
    private javax.swing.JLabel i27;
    private javax.swing.JLabel i28;
    private javax.swing.JLabel i29;
    private javax.swing.JLabel i3;
    private javax.swing.JLabel i30;
    private javax.swing.JLabel i31;
    private javax.swing.JLabel i32;
    private javax.swing.JLabel i33;
    private javax.swing.JLabel i34;
    private javax.swing.JLabel i35;
    private javax.swing.JLabel i36;
    private javax.swing.JLabel i37;
    private javax.swing.JLabel i38;
    private javax.swing.JLabel i39;
    private javax.swing.JLabel i4;
    private javax.swing.JLabel i40;
    private javax.swing.JLabel i41;
    private javax.swing.JLabel i42;
    private javax.swing.JLabel i5;
    private javax.swing.JLabel i6;
    private javax.swing.JLabel i7;
    private javax.swing.JLabel i8;
    private javax.swing.JLabel i9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField playertxt;
    // End of variables declaration//GEN-END:variables
}
