/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package connect4;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Toshiba
 */ 
public class intro extends javax.swing.JFrame {

    /**
     * Creates new form intro
     */
    static Clinet Playerone; // Player one clinet
    static Clinet PlayerTow; // Player Tow Clinet
    static MyBasicServer GamesServer;//servee of game
    final static String ip = "127.0.0.1";//ip
    final static int port = 1234;//port
    static String nameplayerone, nameplayertow;

    public intro() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        PlayBtu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Payer1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Player2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/connect4/intro.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 800));
        setPreferredSize(new java.awt.Dimension(550, 550));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setLabelFor(this);
        jLabel1.setText("Welcome to  4connect Game");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 110, 308, 42);

        PlayBtu.setBackground(new java.awt.Color(0, 255, 51));
        PlayBtu.setFont(new java.awt.Font("Traditional Arabic", 1, 12)); // NOI18N
        PlayBtu.setForeground(new java.awt.Color(51, 51, 255));
        PlayBtu.setText("Play ");
        PlayBtu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayBtuActionPerformed(evt);
            }
        });
        getContentPane().add(PlayBtu);
        PlayBtu.setBounds(330, 290, 120, 30);

        jLabel2.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 255, 255));
        jLabel2.setText("Player1");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 200, 70, 29);
        getContentPane().add(Payer1);
        Payer1.setBounds(160, 200, 171, 29);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 255, 255));
        jLabel3.setText("Player2");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 250, 50, 22);
        getContentPane().add(Player2);
        Player2.setBounds(160, 250, 171, 29);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/connect4/intro.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 10, 550, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PlayBtuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayBtuActionPerformed
        if (!Payer1.getText().isEmpty() && !Player2.getText().isEmpty()) {
            // TODO add your handling code here:
          //  GamesServer = new Server(port);
            ///GamesServer.Startserver();
            Playerone = new Clinet(ip, port);
            PlayerTow = new Clinet(ip, port);
            Playerone.StartClinet();
            PlayerTow.StartClinet();
            nameplayerone = Payer1.getText();
            nameplayertow = Player2.getText();
            this.setVisible(false);
            new wait().setVisible(true);

        } else {
            JOptionPane.showMessageDialog(this, " you  to fill  all the text file ");
        }


    }//GEN-LAST:event_PlayBtuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
            * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
            */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(intro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(intro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(intro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(intro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
            
            
            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new intro().setVisible(true);
                }
            });
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(intro.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(intro.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(intro.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(intro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Payer1;
    private javax.swing.JButton PlayBtu;
    private javax.swing.JTextField Player2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
